# as ações abaixo foram escolhidas 'à mão' e são as mais negociadas 
# no mercado americano e brasileiro. O critério de escolha foi a
# liquidez (volume de negociação)

simbolos = \
{"US": ['^GSPC', 
               'AAPL', 'MSFT', 'AMZN', 'GOOG', 'GOOGL', 
               'META', 'TSLA', 'BRK-B', 'V', 'JNJ', 
               'JPM', 'WMT', 'NVDA', 'UNH', 'MA', 
               'PG', 'HD', 'DIS', 'BAC', 'PYPL', 
               'CMCSA', 'VZ', 'ADBE', 'NFLX', 'KO', 
               'XOM', 'PEP', 'T', 'PFE', 'INTC', 
               'MRK', 'CSCO', 'ABT', 'CRM', 'CVX', 
               'ABBV', 'TMO', 'ACN', 'NKE', 'AVGO', 
               'MCD', 'COST', 'QCOM', 'NEE', 'TXN', 
               'DHR', 'MDT', 'HON', 'UNP', 'LIN', 
               'AMGN', 'PM', 'SBUX', 'LLY', 'UPS', 
               'LOW', 'AMT', 'IBM', 'CAT', 'GILD', 
               'MMM', 'MO', 'GE', 'CHTR', 'NOW', 
               'BLK', 'INTU', 'SPGI', 'ISRG', 'AMD', 
               'CVS', 'ZTS', 'PLD', 'AXP', 'TGT', 
               'FIS', 'APD',  'MDLZ', 'ADP', 'LMT', 
               'CME', 'DUK', 'CL', 'ICE', 'BDX', 
               'CB', 'SPG', 'CI', 'NSC', 'VRTX', 
               'CCI', 'RTX', 'TMUS', 'BKNG', 'DE', 
               'TJX', 'SYK', 'TFC'],

"BR": ['BOVA11.SA', 
               'ABEV3.SA', 'AGRO3.SA', 'ALPA3.SA', 'ALUP11.SA', 'ANIM3.SA', 
               'ARZZ3.SA', 'B3SA3.SA', 'BAZA3.SA', 'BBAS3.SA', 'BBDC3.SA', 
               'BBSE3.SA', 'BEEF3.SA', 'BEES3.SA', 'BHIA3.SA', 'BMEB3.SA', 
               'BNBR3.SA', 'BRAP3.SA', 'BRFS3.SA', 'BRKM3.SA', 'BRSR3.SA', 
               'CCRO3.SA', 'CEEB3.SA', 'CGAS3.SA', 'CIEL3.SA', 'CLSC3.SA', 
               'CMIG3.SA', 'COCE3.SA', 'COGN3.SA', 'CPFE3.SA', 'CPLE3.SA', 
               'CSAN3.SA', 'CSMG3.SA', 'CSNA3.SA', 'CVCB3.SA', 'CYRE3.SA', 
               'DASA3.SA', 'DIRR3.SA', 'DXCO3.SA', 'ECOR3.SA', 'EGIE3.SA', 
               'ELET3.SA', 'EMBR3.SA', 'ENAT3.SA', 'ENEV3.SA', 'ENGI11.SA', 
               'ENGI3.SA', 'EQPA3.SA', 'EQTL3.SA', 'EVEN3.SA', 'EZTC3.SA', 
               'FLRY3.SA', 'FRAS3.SA', 'GGBR3.SA', 'GOAU3.SA', 'GRND3.SA', 
               'GUAR3.SA', 'HYPE3.SA', 'ITSA3.SA', 'ITUB3.SA', 'JBSS3.SA', 
               'JHSF3.SA', 'KEPL3.SA', 'KLBN11.SA', 'KLBN3.SA', 'LEVE3.SA', 
               'LIGT3.SA', 'LOGN3.SA', 'LREN3.SA', 'MDIA3.SA', 'MGLU3.SA', 
               'MILS3.SA', 'MOAR3.SA', 'MRFG3.SA', 'MRVE3.SA', 'MULT3.SA', 
               'MYPK3.SA', 'ODPV3.SA', 'OFSA3.SA', 'PETR3.SA', 'PNVL3.SA', 
               'POMO3.SA', 'POSI3.SA', 'PRIO3.SA', 'PSSA3.SA', 'RADL3.SA', 
               'RAIL3.SA', 'RANI3.SA', 'RAPT3.SA', 'RENT3.SA', 'ROMI3.SA', 
               'SANB11.SA', 'SANB3.SA', 'SBSP3.SA', 'SCAR3.SA', 'SLCE3.SA', 
               'SMTO3.SA', 'TAEE11.SA', 'TASA3.SA', 'TEND3.SA', 'TGMA3.SA', 
               'TIMS3.SA', 'TOTS3.SA', 'TRPL3.SA', 'TUPY3.SA', 'UGPA3.SA', 
               'UNIP3.SA', 'USIM3.SA', 'VALE3.SA', 'VIVT3.SA', 'VLID3.SA', 
               'VULC3.SA', 'WEGE3.SA', 'WHRL3.SA', 'YDUQ3.SA']}